import { notFound } from 'next/navigation';
import Link from 'next/link';
import { AppShell } from '@/components/app-shell';
import { formatDisplayAmount } from '@/lib/token-amounts';
import { getEnabledMarkets } from '@/server/market-registry';
import { readBuyRequest } from '@/server/buy-requests';
import { BuyRequestActions } from '@/features/buy-requests/buy-request-actions';
import { getEnvironment } from '@/server/env';

export const dynamic = 'force-dynamic';
export default async function BuyRequestPage({ params }: { params: Promise<{ requestAddress: string }> }) { const { requestAddress } = await params; const request = await readBuyRequest(requestAddress); if (!request) notFound(); const market = getEnabledMarkets().find(item => item.quoteMint === request.escrowMint); if (!market) notFound(); return <AppShell><section className="mx-auto max-w-3xl"><p className="font-mono text-xs text-text-tertiary">BUY REQUEST</p><h1 className="mt-3 text-3xl font-medium text-text-primary">{request.status === 'active' ? 'Sealed in next Batch' : 'Request canceled'}</h1><p className="mt-3 text-text-secondary">{request.status === 'active' ? 'Your quote funds are locked and your request can participate while it remains active.' : 'This request cannot enter matching.'}</p><dl className="mt-8 space-y-4 text-sm"><Fact label="Private terms" value="Sealed"/><Fact label="Quote escrowed" value={`${formatDisplayAmount(request.escrowRawAmount, 6)} ${market.quoteSymbol} (${request.escrowRawAmount} raw)`}/><Fact label="Quote spent" value={`${request.spentQuoteAmount} raw`}/><Fact label="Quote refundable" value={`${request.refundableQuoteAmount} raw`}/><Fact label="Request expires" value={new Date(Number(request.expiresAt) * 1000).toLocaleString()}/><Fact label="Stock recipient" value={request.recipient}/><Fact label="Commitment fingerprint" value={request.commitmentFingerprint}/><Fact label="Request address" value={request.address}/><Fact label="Escrow address" value={request.escrow}/></dl><p className="mt-8 text-sm text-text-secondary">Matching details need attention until a coordinator ingress is configured. Your request remains governed by its onchain escrow.</p><BuyRequestActions request={request.address} buyer={request.buyer} marketId={market.id} programAddress={getEnvironment().BAZO_PROGRAM_ID} marketAddress={request.market} quoteMint={market.quoteMint} quoteTokenProgram={market.quoteTokenProgram} status={request.status}/><Link href={`/markets/${market.id}`} className="mt-6 inline-flex min-h-11 items-center border border-line-default px-4 text-sm text-text-primary">Back to Market</Link></section></AppShell>; }
function Fact({ label, value }: { label: string; value: string }) { return <div className="border-b border-line-subtle pb-3"><dt className="text-text-tertiary">{label}</dt><dd className="mt-1 break-all font-mono text-text-primary">{value}</dd></div>; }
